### ISSUE TITLE
Issues while loading

### ISSUE THREAD

**Issue by Majklovitch** [kadenscott/Crash#2]
Hello,
me and my friend are running Yatopia minecraft server on version 1.16.5 with Java 9. The problem is, that we tried your plugin, and it did errors in console that the compiled version of this plugin is not matching our version of Java SE. So i tried it with Java 15 on my main computer and it recognized that i have this plugin installed, but it can't load. So please find that issue and reapir it.

Thanks a lot,
MajkCzech

**Comment by Majklovitch** [comment]
The following issue:
[09:49:37 WARN]: AsyncLogger error handling event seq=41, value='Error occurred while enabling CasinoCrash v1.0.3 (Is it up to date?)':
[09:49:37 WARN]: org.apache.logging.log4j.core.appender.AppenderLoggingException: An exception occurred processing Appender ServerGuiConsole
[09:49:37 WARN]:        at org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:75)[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.handleAppenderError(AppenderControl.java:165)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:158)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:337)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29)
[09:49:37 WARN]:        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
[09:49:37 WARN]:        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
[09:49:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[09:49:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[09:49:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[09:49:37 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[09:49:37 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:823)
[09:49:37 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[09:49:37 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:510)
[09:49:37 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:465)
[09:49:37 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144)
[09:49:37 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216)
[09:49:37 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122)
[09:49:37 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
[09:49:37 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[09:49:37 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[09:49:37 WARN]:        at dev.kscott.dependencies.inject.internal.Messages.redBold(Messages.java:306)
[09:49:37 WARN]:        at dev.kscott.dependencies.inject.spi.ErrorDetail.lambda$format$0(ErrorDetail.java:59)
[09:49:37 WARN]:        at java.base/java.util.Optional.map(Optional.java:258)
[09:49:37 WARN]:        at dev.kscott.dependencies.inject.spi.ErrorDetail.format(ErrorDetail.java:59)
[09:49:37 WARN]:        at dev.kscott.dependencies.inject.internal.Messages.formatMessages(Messages.java:90)
[09:49:37 WARN]:        at dev.kscott.dependencies.inject.ProvisionException.getMessage(ProvisionException.java:60)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:134)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEvent.getThrownProxy(RingBufferLogEvent.java:330)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:333)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:323)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:208)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:57)
[09:49:37 WARN]:        at com.mojang.util.QueueLogAppender.append(QueueLogAppender.java:39)
[09:49:37 WARN]:        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
[09:49:37 WARN]:        ... 16 more

**Comment by webcrawls** [comment]
I haven't seen this specific issue before, but CasinoCrash doesn't support yatopia and never will. It's an unstable server platform which should never be ran in production, and can potentially cause issues like the one your seeing here.

If you can replicate this on Paper or Spigot, please open another issue (or join my Discord).
